[package]
name = "snake-game-rust"
version = "0.1.0"
authors = ["Vincenzo Scalcione <vincenzo99.scalcione@gmail.com>"]
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.74.0"
rand = "0.3"

